theme: jekyll-remote-theme
remote_theme: BDHU/minimalist
title: FMRIB MR Spectroscopy Group
description: Website for the FMRIB MR Spectrsocopy Group, University of Oxford
logo: /assets/img/fsleyes.png